services:
  mysql:
    image: mysql
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD_ROOT}
    volumes:
      - ./mysql:/var/lib/mysql
      - ./datos.sql:/docker-entrypoint-initdb.d/datos.sql
    ports:
      - ${DB_PORT}:3306
    container_name: mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8100:80
    environment:
      - PMA_HOST=mysql


